### ISSUE TITLE
crash on latest release code

### ISSUE THREAD

**Issue by kingxt** [ksvc/KSYMediaEditorKit_iOS#1]
pod 'KSYMediaEditorKit', :git => 'https://github.com/ksvc/KSYMediaEditorKit_iOS.git', :tag => 'v0.5.2'
pod 'KSYMediaPlayer_iOS', :git => 'https://github.com/ksvc/KSYMediaPlayer_iOS.git', :tag => 'v2.3.0'

KSYCameraRecorder.stopRecord() crash 

必现

原因是你们git里面sdk版本不一致导致

**Comment by alanwang-dev** [comment]
会在下一个版本（v0.6.x）支持pod方式集成，目前demo中采用的是本地库的方式集成

**Comment by alanwang-dev** [comment]
@kingxt pod v0.7.4即可
