### ISSUE TITLE
KSYMediaEditor startProcessVideo 时内存暴涨

### ISSUE THREAD

**Issue by zhuangyz** [ksvc/KSYMediaEditorKit_iOS#10]
KSYMediaEditor 执行 startProcessVideo 的时候内存会瞬间暴涨 二三十M，这是正常情况吗？

**Comment by alanwang-dev** [comment]
@zhuangyz 合成是一个全速转码过程，开启解码器，编码器，还会有解码缓存列表缓存，如果增加其他贴纸、滤镜、bgm等功能均会在合成时增加内存和CPU

**Comment by zhuangyz** [comment]
嗯嗯，了解。
那我可以通过对原视频进行哪些预处理从而降低合成时的内存消耗吗？
然后合成的时间对于1分钟及以上的视频有点久（1分钟合成大概要30秒左右），我可以通过对视频进行哪些预处理来缩短合成时间吗？

**Comment by zhuangyz** [comment]
恩恩，OK。谢谢
