### ISSUE TITLE
新版本SDK,视频添加音乐合成后有问题

### ISSUE THREAD

**Issue by guatiantian** [ksvc/KSYMediaEditorKit_iOS#7]
KSYMediaEditorKit1.3.0
该版本视频添加音乐合成后，音乐断断续续。

**Comment by zhuangyz** [comment]
我也有这个问题。

**Comment by alanwang-dev** [comment]
@guatiantian @zhuangyz 已找到问题，v1.4.0会fix

**Comment by alanwang-dev** [comment]
@guatiantian @zhuangyz v1.4.0已上线
